version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: flacjacket
      POSTGRES_USER: flacjacket
      POSTGRES_PASSWORD: flacjacket
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      FLASK_APP: app
      FLASK_ENV: production
      DATABASE_URL: postgresql://flacjacket:flacjacket@postgres/flacjacket
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis

  celery_worker:
    build: ./backend
    command: celery -A app.celery worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://flacjacket:flacjacket@postgres/flacjacket
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - celery_logs:/var/log/celery
    depends_on:
      - postgres
      - redis

  flower:
    build: ./backend
    command: celery -A app.celery flower --port=5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/data
    depends_on:
      - redis
      - celery_worker

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001
    ports:
      - "3003:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_uploads:
  celery_logs:
  flower_data:
