name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test with Docker Compose
        run: |
          docker compose build
          docker compose up -d
          # Wait for services to be ready
          docker compose run --rm backend pytest -v
          docker compose down

      - name: Show logs on failure
        if: failure()
        run: docker compose logs
